title: Adi Beniluz's Site
author: abeniluz
email: abeniluz@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  Learn about my interest, hobbies, accomplishments and more. I am currently an AP Computer Science - A student.
  I love art and athletics. Some of my favorite sports are ice hockey, soccer, snowboarding, and kitesurfing.
theme: minima

# social links
instagram_username: adi_beniluz
snapchat_username: abeniluz10
github_username:  abeniluz

show_excerpts: true # set to false to remove excerpts on the homepage
